### ISSUE TITLE
Mejorar el componente TextField

### ISSUE THREAD

**Issue by Less-parrot** [compose-projects/socialLocal#21]
Para esto diríjase a la ruta `org.compose_projects.socialocal.ui.components` abra el archivo  **`TextFieldComponent`** 

1. Refactorizar cada dato al inglés
2. Usar Interface para cambiar de colores
3. Agregar funcionalidad para mostrar y no mostrar lo que el usuario dijite
4. Cambiar tamaño de fuente por defecto(en dispositivos pequeños se corrompe el texField)

**Comment by Less-dev** [comment]
Se mejoró el componente textField  y se añadieron temas por defecto
![upgrade_textField_light](https://github.com/compose-projects/socialLocal/assets/166412593/158a2f91-6e8c-4a4d-a2e5-4dbbbcedfc6f)
*** 
![upgrade_textField_dark](https://github.com/compose-projects/socialLocal/assets/166412593/22272a33-3dc1-4a05-af70-9ebad521fd99) 
-> #23
