### ISSUE TITLE
Agregar componente bottom_chat

### ISSUE THREAD

**Issue by Less-parrot** [compose-projects/socialLocal#22]
Agregar componente visual de bottom_chat, con este diseño:
![bottom_chat](https://github.com/compose-projects/socialLocal/assets/124411052/ef1fbd2a-5a3d-497b-a6aa-d2dd419f3b60),

## ¿Cómo lo hago? 

1. Diríjase al paquete `org.compose_projects.socialocal.ui.components`.
2. Creé un nuevo paquete llamado **`bottom_chat`**.
3. Diseñe el campo de texto usando nuestro componente _`TextFieldComponent`_ que se encuentra en el mismo paquete.
4. Con un Row horizontalmente alineé un IconButton de envio de notas de voz.

## A tener en cuenta:

1. Solo se diseñará la parte visual, para la parte funcional usar funciones lambda.
2. Hacer que se pueda cambiar de estilo fácilmente.
3. Dejar un estilo por defecto, como el que se vé en la imagen de referencia.

**Comment by Less-dev** [comment]
Se hizo el compoenente bottom chat 
![bottom_chat_dark](https://github.com/compose-projects/socialLocal/assets/124411052/cd042948-e1e7-4e47-a632-518993b09506)
***
![bottom_chat_light](https://github.com/compose-projects/socialLocal/assets/124411052/4879fe75-ff80-4448-9d3e-da65455b5223)
